### ISSUE TITLE
Support for Retrofit2 adapter

### ISSUE THREAD

**Issue by mew22** [josesamuel/RxRemote#2]
Hello,
Thanks for your remote observable. Do you have plan to support it as an adapter call for the well known android rest library Retrofit as RxJavaAdapters, to use it throught aidl too ?

https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava

Best regards,
Sebastien

**Comment by josesamuel** [comment]
Thanks for the suggestion, will definitely consider adding that soon

**Comment by mew22** [comment]
Thanks, let me know if you handle this :)

**Comment by josesamuel** [comment]
Version 1.0.13 released... Simply use the retrofit-adapters/rxjava adapter, then wrap the returned Observable with RemoteObservable

**Comment by mew22** [comment]
Thanks
