### ISSUE TITLE
Does RxRemote is affected by binder 1mb limit ?

### ISSUE THREAD

**Issue by mew22** [josesamuel/RxRemote#3]
From this link, I can read:
http://developer.android.com/reference/android/os/TransactionTooLargeException.html

"During a remote procedure call, the arguments and the return value of the call are transferred as Parcel objects stored in the Binder transaction buffer. If the arguments or the return value are too large to fit in the transaction buffer, then the call will fail and TransactionTooLargeException will be thrown.
The Binder transaction buffer has a limited fixed size, currently 1Mb, which is shared by all transactions in progress for the process. "

I bypass this limitation in aidl by sending a ParcelFileDescriptor, create a pipe and send data thought it. I am new to Observable and I don't know your implementation, if I use RemoteObservable<List<Toto>> with List<Toto>  greater than 1mb, will it work?

**Comment by josesamuel** [comment]
It will have the inherent limitations of binder limits. 

You could pass any Parcelable as the type. 

Pager https://github.com/josesamuel/pager can also be returned, which dynamically only fetches the data that is actually fetched.
